<!-- Criado por Djonathan Quadras -->

# Questão 1.8 {-}

```{r, echo=FALSE, include=FALSE}
source("scripts/solution108.R", local = knitr::knit_global())
source("scripts/enunciados.R", local = knitr::knit_global())
dados <- selecionaDados(questao108, params$modelo)
sol <- solution(dados)
```

Um transformador trifásico abaixador de `r dados$S` VA, `r dados$V1`/`r dados$V2` V, `r dados$f` Hz, ligado em $Y$/$\Delta$ foi submetido a um ensaio de curto-circuito realizado pelo lado de baixa tensão (`r dados$V2`V) de onde se obteve a seguinte impedância equivalente, por fase: `r dados$Z` [$\Omega$]. Os seguintes resultados foram obtidos de um ensaio de circuito aberto, realizado pelo lado de baixa tensão, a `r dados$f` Hz: $P_{3\phi}$ = `r dados$P3PHI` W; $I_l$ = `r dados$IL` A; $V_l$ = `r dados$VL` V. O equipamento está alimentando uma carga trifásica equilibrada de `r dados$CARGA`W, com um fator de potência `r dados$FP` adiantado. A tensão na carga foi ajustada para `r dados$V2` V.

Para a sua versão, pede-se:

a. A tensão na fonte, a corrente e a potência aparente fornecidas pela fonte, referidas ao primário (lado 1), e o fator de potência “visto” pela fonte, usando o modelo impedância série;
b. O rendimento e a regulação do transformador, usando o modelo impedância série. Usar a potência do ensaio a vazio, se realizado com tensão nominal;
c. Comentar os resultados!

## Resolução {-}

Inicialmente, para facilitar os cálculos, será feita a conversão do formato $\Delta$ para um formato Y. Assim,

$$
Z_{eq} = \frac{`r dados[["Z"]]`}{3} \implies \boxed{`r round(sol[["ZEQ"]],4)`\Omega} 
$$

Tem-se do enunciado do problema para o primário uma tensão de `r round(sol$vBTLinha,2)`V de linha e `r round(sol$vATFase,2)`V de fase, além de uma tensão no secundário de `r round(sol$vBTLinha,2)`V de linha e  `r round(sol$vBTFase,2)`V de fase no estrela equivalente. Assim, será utilizado um fator de conversão de 

$$
a = \frac{`r round(sol[["vATFase"]],2)`}{`r round(sol[["vBTFase"]],2)`} \quad \boxed{a = `r round(sol[["a"]],2)`}
$$

Desse modo, tem-se a impedância equivalente

$$
\boxed{Z_{eq} = `r round(sol[["zeqPRI"]],2)` = `r round(Mod(sol[["zeqPRI"]]),2)` \angle (`r round(rad2degree(Arg(sol[["zeqPRI"]])),2)`)^\circ\Omega}
$$

Também é possível encontrar a tensão na carga fazendo-se $V_c = aV_c$. Assim: $V_c = `r round(sol[["vcr"]],2)`$V. É possível calcular a corrente na carga por meio de $P_{c_{3\phi}} = \sqrt{3}V_c I_c fp$. Assim:

$$
I_{c} = `r dados[["FP"]]`\frac{`r dados[["CARGA"]]`}{\sqrt{3}`r dados[["V1"]]`} \implies \boxed{I_{c} = `r round(Mod(sol[["ic"]]),2)` \angle (`r round(rad2degree(Arg(sol[["ic"]])),2)`)^\circ A}
$$

Com o valor da corrente de saída, e sabendo que $I_e = aI_c$, tem-se que a corrente de entrada é de

$$
\boxed{I_e = `r round(sol[["ie"]],2)` A =  `r round(Mod(sol[["ie"]]),2)` \angle (`r round(rad2degree(Arg(sol[["ie"]])),2)`)^\circ A}
$$


Com a corrente de entrada, tensão na carga e impedâncias do circuito, é possível agora calcular a tensão na fonte (pelo lado secundário) por meio das Tensões de Kirchhoff.

$$
V_e = (Z_T)(I_e) + V_c = (`r round(sol[["zeqPRI"]],2)`)(`r round(sol[["is"]],2)`) + `r round(sol[["vcr"]],2)`
$$

Assim,

$$
V_e = `r round(sol[["ve"]],2)` = `r round(Mod(sol[["ve"]]),2)` \angle `r round(rad2degree(Arg(sol[["ve"]])),2)` ^\circ V
$$

Com os valores de $V_e$ e $I_e$, é possível calcular $S_e$ por meio de $S_e = \sqrt{3} I_e V_e$. Assim, $S_e = `r round(sol[["se"]],2)`VA$. O fator de potência na fonte é de $fp_e = \cos(\theta_v-\theta_i) = `r round(sol[["fpe"]],2)`$

O rendimento é calculado como

$$
\Re = \frac{|V_e|-|V_s|}{|V_s|} = \frac{`r round(Mod(sol[["ve"]]),2)` - `r round(Mod(sol[["vcr"]]),2)`}{`r round(Mod(sol[["vcr"]]),2)`} = `r round(sol[["re"]],2)` \implies \Re = `r round(100*sol[["re"]],2)` \%
$$

A regulação é definida por

$$
\eta = \frac{P_{s3\phi}}{P_{e3\phi}} = \frac{P_{s3\phi}}{P_{s3\phi} +P_{f3\phi}+P_{j3\phi}+P_{sup3\phi}}
$$

Assim,


$$
\eta = \frac{`r dados[["CARGA"]]`}{`r dados[["CARGA"]]` + `r dados[["P3PHI"]]` + `r sol[["pj3phi"]]` + 0} \implies \eta =`r round(100*sol[["n"]],2)` \%
$$

