<!-- Criado por Djonathan Quadras -->

# Questão 1.10 {-}


```{r, echo=FALSE, include=FALSE}
source("scripts/solution110.R", local = knitr::knit_global())
source("scripts/enunciados.R", local = knitr::knit_global())
dados108 <- selecionaDados(questao108, params$modelo)
dados110 <- selecionaDados(questao110, params$modelo)
sol <- solution(dados108, dados110)
```

Os dois transformadores abaixo são ligados em paralelo para alimentar uma carga trifásica equilibrada.

**TRANSFORMADOR 1:** Um transformador trifásico abaixador de `r dados108$S` VA, `r dados108$V1`/`r dados108$V2` V, `r dados108$f` Hz, ligado em $Y$/$\Delta$ foi submetido a um ensaio de curto-circuito realizado pelo lado de baixa tensão (`r dados108$V2`V) de onde se obteve a seguinte impedância equivalente, por fase: `r dados108$Z` [$\Omega$]. Os seguintes resultados foram obtidos de um ensaio de circuito aberto, realizado pelo lado de baixa tensão, a `r dados108$f` Hz: $P_{3\phi}$ = `r dados108$P3PHI` W; $I_l$ = `r dados108$IL` A; $V_l$ = `r dados108$VL` V.

**TRANSFORMADOR 2:** Um transformador trifásico abaixador de `r dados110$S` VA, `r dados110$V1`/`r dados110$V2` V, `r dados110$f` Hz, ligado em $Y$/$\Delta$ foi submetido a um ensaio de curto-circuito realizado pelo lado de baixa tensão (`r dados110$V2`V) de onde se obteve a seguinte impedância equivalente, por fase: `r dados110$Z` [$\Omega$]. Os seguintes resultados foram obtidos de um ensaio de circuito aberto, realizado pelo lado de alta tensão, a `r dados110$f` Hz: $P_{3\phi}$ = `r dados110$P3PHI` W; $I_l$ = `r dados110$IL` A; $V_l$ = `r dados110$VL` V.

Se o conjunto está alimentando uma carga nominal (tensão e corrente nominais), sob fator de potência $0.6$ capacitivo, pede-se:

a.  A tensão na fonte, a corrente e a potência aparente fornecidas pela fonte e por cada transformador em paralelo, referidas ao primário (lado 1), e o fator de potência “visto” pela fonte e o fator de potência de cada transformador, usando o modelo impedância série;
b. O rendimento e a regulação de cada transformador;
c. Comentar os resultados! 

## Resolução {-}

Para o lado primário, é considerado uma tensão de `r round(dados108$V1,2)`V de linha e `r round(sol$solTrafo1$vATFase,2)`V de fase, além de uma tensão no secundário de `r round(dados108$V2,2)`V de linha e  `r round(sol$solTrafo1$vBTFase,2)`V de fase no estrela equivalente. Assim, será utilizado um fator de conversão igual

$$
a = \frac{`r round(sol[["solTrafo1"]][["vATFase"]],2)`}{`r round(sol[["solTrafo1"]][["vBTFase"]],2)`} \quad \boxed{a = `r round(sol[["solTrafo1"]][["a"]],2)`}
$$


Inicialmente, transforma-se as impedâncias para o seu modelo estrela equivalente (ao lado primário).

$$
Z_{eq1Y} = a\frac{`r dados108[["Z"]]`}{3}  \quad Z_{eq2Y} = a\frac{`r dados110[["Z"]]`}{3}
$$

Assim,

$$
\boxed{Z_{eq1} = `r round(sol[["solTrafo1"]][["zyEqPri"]],2)` = `r round(Mod(sol[["solTrafo1"]][["zyEqPri"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solTrafo1"]][["zyEqPri"]])),2)`)^\circ\Omega}  \quad \text{ e } \quad \boxed{Z_{eq2} =  `r round(sol[["solTrafo2"]][["zyEqSec"]],2)` = `r round(Mod(sol[["solTrafo2"]][["zyEqPri"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solTrafo2"]][["zyEqPri"]])),2)`)^\circ\Omega}
$$

Também é possível encontrar a tensão na carga fazendo-se $V_c = aV_{c_{fase}}$. Assim: $V_c = `r round(sol[["solTrafo1"]][["vcr"]],2)`$V. É possível calcular a corrente na carga por meio de $P_{c_{3\phi}} = \sqrt{3}V_{c_{linha}}I_{c_{linha}}fp$. Assim:

$$
I_{c} = `r dados110[["FP"]]`\frac{`r dados108[["CARGA"]]`}{\sqrt{3}`r dados108[["V1"]]`} \implies \boxed{I_{c} = `r round(Mod(sol[["solCarga"]][["ic"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solCarga"]][["ic"]])),2)`)^\circ A}
$$

Com isso, é possível calcular as correntes de saída de ambos os transformadores por meio de

$$
I_1 = \frac{Z_{eq2}}{Z_{eq1}}I_2 \quad \text{ e } \quad I_1 + I_2 = I_c
$$

Assim, tem-se

$$
\boxed{I_1 =  `r round(sol[["solTrafo1"]][["ic"]],2)`A = `r round(Mod(sol[["solTrafo1"]][["ic"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solTrafo1"]][["ic"]])),2)`)^\circ A}  \quad \text{ e } \quad  \boxed{I_2 = `r round(sol[["solTrafo2"]][["ic"]],2)` = `r round(Mod(sol[["solTrafo2"]][["ic"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solTrafo2"]][["ic"]])),2)`)^\circ A}
$$

Assim, é possível descobrir a potência fornecida por cada transformador fazendo-se $S = VI$. Tem-se, então:

$$
\boxed{S_1 =  `r round(Mod(sol[["solTrafo1"]][["ss"]]),2)` VA}  \quad \text{ e } \quad  \boxed{S_2 = `r round(Mod(sol[["solTrafo2"]][["ss"]]),2)`VA}
$$

Com o valor da corrente de saída, e sabendo que $I_e = aI_c$, tem-se que a corrente de entrada é de

$$
\boxed{I_e = `r round(sol[["solCarga"]][["ie"]],2)` A =  `r round(Mod(sol[["solCarga"]][["ie"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solCarga"]][["ie"]])),2)`)^\circ A}
$$

Tendo a corrente de saída, os valores das impedâncias e o valor da tensão na carga é possível encontrar o valor de tensão na fonte fazendo-se $V_e = (Z_{eq1}||Z_{eq2})I_e + Vc$. Assim,

$$
V_e = (`r round(sol[["solCarga"]][["Zpar"]],2)`)(`r round(sol[["solCarga"]][["ie"]],2)`) + `r round(sol[["solTrafo1"]][["vcr"]],2)` \implies \boxed{V_e = `r round(sol[["solCarga"]][["ve"]],2)` V = `r round(Mod(sol[["solCarga"]][["ve"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solCarga"]][["ve"]])),2)`)^\circ V}
$$

Com os valores de $V_e$ e $I_e$, é possível calcular $S_e$ por meio de $S_e = \sqrt{3} I_e V_e$. Assim, $S_e = `r round(sol[["solCarga"]][["sfonte"]],2)`VA$. O fator de potência na fonte é de $fp_e = \cos(\theta_v-\theta_i) = `r sol[["solCarga"]][["fpfonte"]]`$

Com os valores de impedância, corrente de saída e tensões, é possível determinar a tensão de entrada de cada um dos dois transformadores.

$$
\boxed{V_{e1} =  `r round(Mod(sol[["solTrafo1"]][["ve"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solTrafo1"]][["ve"]])),2)`)^\circ V}  \quad \text{ e } \quad  \boxed{V_{e2} = `r round(Mod(sol[["solTrafo2"]][["ve"]]),2)` \angle (`r round(rad2degree(Arg(sol[["solTrafo2"]][["ve"]])),2)`)^\circ V}
$$

Com os valores de tensão e corrente é possível determinar o fator de potência de entrada de cada um dos dois transformadores.

$$
\boxed{fp_1 =  `r round(sol[["solTrafo1"]][["fp"]],2)`}  \quad \text{ e } \quad  \boxed{fp_2 = `r round(sol[["solTrafo2"]][["fp"]],2)`}
$$

O rendimento dos dois transformadores é dado por $\Re = \frac{V_e-V_s}{V_s}$, então.

$$
\boxed{\Re_1 =  `r round(100*sol[["solTrafo1"]][["re"]],2)`\%}  \quad \text{ e } \quad  \boxed{\Re_2 = `r round(100*sol[["solTrafo2"]][["re"]],2)`\%}
$$

Por fim, a regulação dos dois transformadores é dado por $\eta = \frac{P_{s3\phi}}{P_{e3\phi}}$, então.

$$
\boxed{\eta_1 =  `r round(100*sol[["solTrafo1"]][["n"]],2)`\%}  \quad \text{ e } \quad  \boxed{\eta_2 = `r round(100*sol[["solTrafo2"]][["n"]],2)`\%}
$$
